name: Generate Snake

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Generate the GitHub contribution grid snake (light and dark)
      - name: Generate GitHub Contribution Snake
        uses: platane/snk/svg-only@v3
        with:
          github_user_name: AZAR2305
          output: dist/github-contribution-grid-snake.svg
          dark_mode: true   # enable dark mode

      # Push the generated SVGs back to main
      - name: Commit and Push Snake
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Update GitHub contribution snake"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
