name: Generate Snake

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v3

    # Generate the snake files in ./dist/
    - name: Generate github-contribution-grid-snake.svg
      uses: Platane/snk/svg-only@v3
      with:
        github_user_name: AZAR2305
        outputs: |
          dist/github-contribution-grid-snake.svg
          dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
    # Push the content of <build_dir> to a branch
    - name: Push github-contribution-grid-snake.svg to the output branch
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}